name: Retrieve DB Credentials and Run Script

on:
  workflow_dispatch:

jobs:
  retrieve-credentials-and-run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install -y vault

    - name: Login to Vault
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
        VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      run: |
        vault write -field=token auth/approle/login role_id=${VAULT_ROLE_ID} secret_id=${VAULT_SECRET_ID} > VAULT_TOKEN
        echo "VAULT_TOKEN=$(cat VAULT_TOKEN)" >> $GITHUB_ENV

    - name: Retrieve DB Credentials from Vault
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ env.VAULT_TOKEN }}
      run: |
        DB_USERNAME=$(vault kv get -field=db_username secret/my_db_secret)
        DB_PASSWORD=$(vault kv get -field=db_password secret/my_db_secret)
        echo "DB_USERNAME=${DB_USERNAME}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV

    - name: Run API Post Command with DB Credentials
      env:
        DB_USERNAME: ${{ env.DB_USERNAME }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
      run: |
        curl -s -w "%{http_code}" -X POST -u $DB_USERNAME:$DB_PASSWORD -H "Content-Type: application/json" \
        -d '{ "extra_vars": "{\"change_number\":\"$change_number\"}" }' \
        "$workflow_template" | jq "."
